---

  - name: install git
    become: yes
    apt: 
      name: git
      state: latest

  - name: set umask for all session - configure pam
    become: yes
    lineinfile:
      path: "/etc/pam.d/common-session"
      line: "session optional\tpam_umask.so"

  - name: set umask for all session - configure login definitions
    become: yes
    lineinfile:
      path: "/etc/login.defs"
      regexp: "^UMASK"
      line: "UMASK\t\t027"

  - name: add git user
    become: yes
    user: 
      name: git
      shell: "/usr/bin/git-shell"
      home: "/home/git"
      generate_ssh_key: yes

  - name: git add authorized keys
    become: yes
    authorized_key: 
      user: git
      key: "{{ lookup('file', '{{ remote_access_authorized_keys_prefix }}/{{ item }}.pub') }}"
    loop: "{{ git_access_authorized_users }}"

  - name: create directories for git repositories
    become: yes
    file: 
      path: "{{ item }}"
      owner: "git"
      group: "git"
      mode: "u=rwX,g=rX,o="
      state: directory
    loop: "{{git_repositories}}"

  - name: initialize git repositories
    become: yes
    command:
      chdir: "{{ item }}"
      creates: "{{ item }}/HEAD"
      cmd: "git init --bare"
    loop: "{{git_repositories}}"

  - name: apply credentials to repositories
    become: yes
    file:
      path: "{{ item }}"
      owner: "git"
      group: "git"
      mode: "u+X,g=rX,o="
      state: directory
      recurse: yes
    loop: "{{git_repositories}}"